Implement login
zinza-d2-training/thanhpc-react pull request #16
Opened 2022-02-10 05:01 UTC by cthanh2310

closes #13

2022-02-13 14:52 UTC, hungnp194 approved these changes

2022-02-13 14:52 UTC, hungnp194 commented on src/pages/Login.tsx
> +                      placeholder="password123"
```suggestion
                      placeholder="**************"
```

2022-02-13 14:52 UTC, hungnp194 commented on src/pages/Login.tsx
> +                )}
Dùng thuộc tính helpText của TextField

2022-02-13 14:52 UTC, hungnp194 commented on src/pages/Login.tsx
> +                      !!errors.password?.message ||
Dùng formState isValid

2022-02-13 14:54 UTC, hungnp194 requested changes
Em sửa những cái ở trên nhé.

2022-02-13 15:32 UTC, cthanh2310 commented on src/features/login/loginAPI.ts
> +  return new Promise<{ data: Partial<ResponseLogin> }>((resolve, reject) => {
Để em fix lại em quên fix chỗ ấy ạ

2022-02-14 03:46 UTC, cthanh2310 commented on src/models/User.ts
> +}
Em chưa hiểu lắm ạ.

2022-02-14 03:56 UTC, hungnp194 commented on src/models/User.ts
> +}
@cthanh2310 BaseModel, InsertModel và SetModel đó em. Model đại diện cho table của database. User của em cũng đang thiếu id

2022-02-15 04:52 UTC, hungnp194 approved these changes
LGTM

2022-02-15 04:52 UTC, merged