Implement registration
zinza-d2-training/thanhpc-react pull request #24
Opened 2022-02-21 02:01 UTC by cthanh2310

closes #22

2022-02-21 09:05 UTC, hungnp194 requested changes

2022-02-21 09:05 UTC, hungnp194 commented on src/pages/Register/StepThree.tsx
> +  const [wardId, setWardId] = useState<string>('');
Form quản lý các fieldState rồi, sao lại cần localState nữa?

2022-02-21 09:05 UTC, hungnp194 commented on src/pages/Register/StepThree.tsx
> +                ? listWard.map((value: any) => (
Không dùng any

2022-02-21 09:05 UTC, hungnp194 commented on src/pages/Register/StepTwo.tsx
> +export const StepTwo = (props: any) => {
KHông dùng any

2022-02-21 09:24 UTC, cthanh2310 commented on src/features/login/consts.ts
> +export const fakeAccount: Partial<User> = {
Vì em fake những field cần thiết để đăng nhập chứ k get hết tất cả các field

2022-02-22 06:59 UTC, hungnp194 approved these changes

2022-02-22 06:59 UTC, merged